services:
  - type: web
    name: ti-quiero-ti
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn djangocurd.wsgi:application"
    runtime: python
    pythonVersion: 3.13.4
    plan: free
    autoDeploy: true